name: ci

on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  go-test-postgres:
    name: go-test-postgres
    runs-on: ubuntu-20.04

    services:
      postgres:
        image: postgres:14.2-alpine3.15
        env:
          # These dummy values are only used for local testing purposes.
          POSTGRES_DB: admin
          POSTGRES_PASSWORD: admin
          POSTGRES_USER: admin
        # Set health checks to wait until postgres has started.
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.16"

      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: go mod download && go install

      - name: Build package
        run: go build

      - name: Run go test
        env:
          POSTGRES_URI: postgresql://admin:admin@postgres:5432/admin
        run: go test -run TestDAOCoinLimitOrder -v ./lib
